require: rubocop-rspec

inherit_from: .rubocop_todo.yml

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

# shut hound up
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
