require: rubocop-rspec

inherit_from: .rubocop_todo.yml

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

# shut hound up
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

RSpec/MessageSpies:
  Enabled: false
